### ISSUE TITLE
Document how to design a show from scratch

### ISSUE THREAD

**Issue by nzoschke** [baaahs/sparklemotion#467]
I'm working to understand how this all works, design a show, and contribute some docs improvements and have some questions.

To understand the basic concepts I'm trying to design a simple show from scratch, based on pieces from the "Pasture Bedtime" template.

For the show I'd like two things:

- "Solid Color" paint shader with two controls:
  - Color slider
  - Brightness slider
- "Scanner" filter shader

<img width="471" alt="Screen Shot 2022-07-29 at 8 13 35 PM" src="https://user-images.githubusercontent.com/147410/181867516-a31de6fc-9c2e-4962-9ff7-8462462da2c9.png">

> Stripped down "Pasture Bedtime" show shows a solid color with a vertical scan line!

## Some general questions...

What is the preferred terminology?

- "scenes" vs "paint filters"
- "controls" vs "gadgets"

What are the main UI components?

- Is far left model preview / Open / Show GLSL section always there? Why would I place a "visualizer" in the layout instead?
- What is a "vacuity"?
- What is the "UV In" xy control?

## Building a show

The basic steps are:

- `+ New Show` -> Empty Show
- Design Mode
- `+` -> New Button -> New Paint Shader

    ```cpp
    // Solid Color
    uniform vec4 color; // @@ColorPicker

    // @return color
    // @param uvIn uv-coordinate
    vec4 main(vec2 uvIn) {
        return vec4(color.rgb, 1.);
    }
    ```

  - Shader Name: Solid Color
  - Apply, then Close

- `+` -> New Button -> New Filter Shader

    ```cpp
    // Scanner
    uniform float time;

    // @param fragCoord uv-coordinate
    // @return color
    vec4 upstreamColor(vec2 fragCoord);

    // @return color
    // @param uvIn uv-coordinate
    // @param inColor color
    vec4 main(vec2 uvIn) {
        vec4 c = upstreamColor(uvIn);
        float width = .025;

        float xScan = cos(time) / 2. + .5;
        if (abs(uvIn.x - xScan) < width) {
            c.rgb *= .5;
            c.r = 0.; // 1. - c.r;
        }

        float yScan = sin(time) / 2. + .5;
        if (abs(uvIn.y - yScan) < width) {
            c.rgb *= .5;
            c.g = 0.; //  = 1. - c.g;
        }

        return vec4(c.r, c.g, c.b, 1.);
    }
    ```

- Save Show As... "tutorial.sparkle"

I have two main issues:

1) Placing controls is inconsistent in the UI
2) The shaders don't work as expected

## Placing Controls

The "Unplaced Controls" widget is inconsistent. Sometimes it doesn't show the unplaced controls. Sometimes the drag and drop from the window into the button grid drops the widget immediately in a fixed location. You can overlap buttons and have a hard time hitting the delete or edit.

But eventually I can get it to work with some combination of:

- exit design mode
- reload web browser
- tweak the name of the control variables
- drag a control
- move it to another area in the button grid
- drag another control

## Shaders

The "Solid Color" shader is working as expected! Next step is to extend it to have a alpha or brightness slider.

The "Scanner" shows a warning symbol and doesn't render a horizontal and vertical scan line on the model as it does in the "Pasture Bedtime" show. It does periodically change the brightness of the entire model.

Is there something more to do with ports? Or with the shader code?

<img width="699" alt="Screen Shot 2022-07-29 at 8 36 27 PM" src="https://user-images.githubusercontent.com/147410/181867621-89e98a6c-8b17-4647-839c-a0175e8f4547.png">

> Rebuilt show shows a solid color but no vertical or horizontal scan line...

**Comment by nzoschke** [comment]
The next step for me is to keep hacking on the "Pasture Bedtime" show, as I suspect something in the foundation is just wired up different and better in there... Extending / adding shaders is pretty much working as expected.

But I wanted to open an issue with questions in case I'm missing something simple to start, and would like to help improve the existing docs, write a tutorial, etc.

**Comment by nzoschke** [comment]
Here's an export of my show where the scanner isn't having the visual effect as expected yet.

```json
{
    "title": "Untitled",
    "layouts": {
        "formats": {
            "default": {
                "mediaQuery": null,
                "tabs": [
                    {
                        "type": "Grid",
                        "title": "Main",
                        "columns": 12,
                        "rows": 8,
                        "items": [
                            {
                                "controlId": "visualizer",
                                "column": 9,
                                "row": 0,
                                "width": 3,
                                "height": 2
                            },
                            {
                                "controlId": "solidColor",
                                "column": 0,
                                "row": 0
                            },
                            {
                                "controlId": "scanner",
                                "column": 1,
                                "row": 0
                            },
                            {
                                "controlId": "color",
                                "column": 0,
                                "row": 1,
                                "width": 2,
                                "height": 2
                            },
                            {
                                "controlId": "uvIn",
                                "column": 0,
                                "row": 5
                            }
                        ]
                    }
                ]
            }
        }
    },
    "shaders": {
        "solidColor": {
            "title": "Solid Color",
            "src": "// Solid Color\nuniform vec4 color; // @@ColorPicker\n\n// @return color\n// @param uvIn uv-coordinate\nvec4 main(vec2 uvIn) {\n    return vec4(color.rgb, 1.);\n}\n"
        },
        "scanner": {
            "title": "Scanner",
            "src": "// Scanner\nuniform float time;\n\n// @param fragCoord uv-coordinate\n// @return color\nvec4 upstreamColor(vec2 fragCoord);\n\n// @return color\n// @param uvIn uv-coordinate\n// @param inColor color\nvec4 main(vec2 uvIn) {\n    vec4 c = upstreamColor(uvIn);\n    float width = .025;\n\n    float xScan = cos(time) / 2. + .5;\n    if (abs(uvIn.x - xScan) < width) {\n        c.rgb *= .5;\n        c.r = 0.; // 1. - c.r;\n    }\n\n    float yScan = sin(time) / 2. + .5;\n    if (abs(uvIn.y - yScan) < width) {\n        c.rgb *= .5;\n        c.g = 0.; //  = 1. - c.g;\n    }\n\n    return vec4(c.r, c.g, c.b, 1.);\n}"
        }
    },
    "patches": {
        "solidColor-patch": {
            "shaderId": "solidColor",
            "incomingLinks": {
                "uvIn": {
                    "type": "datasource",
                    "dataSourceId": "uvInXyPad"
                },
                "color": {
                    "type": "datasource",
                    "dataSourceId": "colorColorPicker"
                }
            }
        },
        "scanner-patch": {
            "shaderId": "scanner",
            "incomingLinks": {
                "time": {
                    "type": "datasource",
                    "dataSourceId": "time"
                },
                "uvIn": {
                    "type": "stream",
                    "stream": "main"
                },
                "upstreamColor": {
                    "type": "stream",
                    "stream": "main"
                }
            }
        }
    },
    "controls": {
        "visualizer": {
            "type": "baaahs.Core:Visualizer"
        },
        "solidColor": {
            "type": "baaahs.Core:Button",
            "title": "Solid Color",
            "patchIds": [
                "solidColor-patch"
            ]
        },
        "scanner": {
            "type": "baaahs.Core:Button",
            "title": "Scanner",
            "patchIds": [
                "scanner-patch"
            ]
        },
        "color": {
            "type": "baaahs.Core:ColorPicker",
            "title": "Color",
            "controlledDataSourceId": "colorColorPicker"
        },
        "uvIn": {
            "type": "baaahs.Core:XyPad",
            "title": "Uv In",
            "controlledDataSourceId": "uvInXyPad"
        }
    },
    "dataSources": {
        "uvInXyPad": {
            "type": "baaahs.Core:XyPad",
            "title": "Uv In"
        },
        "colorColorPicker": {
            "type": "baaahs.Core:ColorPicker",
            "title": "Color",
            "initialValue": -1
        },
        "time": {
            "type": "baaahs.Core:Time"
        }
    },
    "version": 8
}
```

**Comment by nzoschke** [comment]
In looking at pasture bedtime template json, I see some stuff that sounds important like:

- baaahs.Core:ModelInfo
- baaahs.Core:PixelLocation
- baaahs.Core:FixtureInfo
- baaahs.Core:Date
- baaahs.Core:PixelIndex
- baaahs.Core:PixelCount

Maybe more foundation stuff to add to my project...

**Comment by xian** [comment]
Ouch, yes to all the (many) bugs in the grid layout UI. Sorry, I keep working on other stuff because, as you say, there are mostly workarounds, but they're very clunky.

Maybe the easiest thing would be to do a call whenever you have a minute and we can go through each of these?

**Comment by xian** [comment]
> What is the preferred terminology?

Yeah, there are lots of artifacts littered about from various stops along the way to my current thinking about domain terms, unfortunately.

> "scenes" vs "paint filters"

A _**scene**_ represents the arrangement of physical lighting fixtures (and their controller mappings), e.g. a particular club or, say, mutant vehicle.

A _**show**_ is the visual effects that can be projected onto a scene. For the most part, shows and scenes can be thought of as orthogonal.

A _**shader**_ is a small program written in GLSL which, combined with some metadata describing how to hook up its inputs and outputs, constitutes a _**patch**_ (in the sense of old analog synths).

There are references in some places to _**shader types**_:
* Paint — given an x/y input, return a color output.
* Filter — given a color input, return a color output.
* Projection — given an x/y/z input, return an x/y output.
* Distortion — given an x/y input, return an x/y output.
* Mover — return pan, tilt, etc. for a moving head fixture.

Shader types are a mostly deprecated concept in the code at this point, though they're maybe helpful for understanding the patch model, and they're handy as templates.

Distinct from the "filter" shader type above, a patch is considered a "filter" if one of its input ports matches the type of its output port. So, a shader that takes a color and returns a color is considered a "filter", and it gets special handling rules when all the active patches are smooshed together into a program. I think it's easier to talk through this one, brain feeling smooshed right now.

> "controls" vs "gadgets"

I've been using "controls" lately. No particularly coherent reasoning there.

> What are the main UI components?

The one that's maybe most important and least obvious is the _button group_, which lets you make a set of buttons mutually exclusive.

> Is far left model preview / Open / Show GLSL section always there? Why would I place a "visualizer" in the layout instead?

That only appears in the simulator; in the production version that whole left panel is gone.

> What is a "vacuity"?

It's an empty spot that unplaced controls will be dropped into. Any control that we consider relevant (i.e. it's in use by some currently active patch), and which isn't already explicitly placed on the grid, will show up in a vacuity.

> What is the "UV In" xy control?

It comes from 3D-world [texture mapping](https://en.wikipedia.org/wiki/UV_mapping). It's a 2D coordinate system from 0,0 (lower-left) to 1,1 (upper-right). It's distinct from the XYZ coordinate system that the scene model lives in, which might be in meters or feet or cm or furlongs or whatever; UV is unitless. Shaders from e.g. shadertoy.com draw into UV, and then we project that onto the model's XYZ coords. It's kinda gritty details that maybe should be better hidden from end users?

**Comment by xian** [comment]
> In looking at pasture bedtime template json, I see some stuff that sounds important like:
> 
> baaahs.Core:ModelInfo
> baaahs.Core:PixelLocation
> baaahs.Core:FixtureInfo
> baaahs.Core:Date
> baaahs.Core:PixelIndex
> baaahs.Core:PixelCount

If you look in the Help tab in the shader editor you'll find snippets of code that let you pull from any of those feeds.

**Comment by xian** [comment]
I'm guessing that your show is behaving weirdly cuz you don't have a default projection shader.

Edit the show's patches by clicking on the pencil up by the show name:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/40298/182488398-1297f6e9-beb5-4109-9685-cdbce7bd47c9.png">

… then add a projection shader, like so:
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/40298/182488671-695f0f08-6c3f-4b32-85b4-b1c91f3c2f97.png">

**Comment by nzoschke** [comment]
This is all very helpful thanks! Didn't find the default projection I'll try that next!
