### ISSUE TITLE
Hi-Res model looks dark

### ISSUE THREAD

**Issue by nzoschke** [baaahs/sparklemotion#477]
Follow up from https://github.com/baaahs/sparklemotion/pull/473#discussion_r939554081

> There's currently a sort-of bug in the template that makes Hi-Res look really dark which I'll fix. (I think the grid w/h just needs to be smaller; LEDs are rendered at a constant size in the visualizer and they're just too spread out right now.)

**Comment by nzoschke** [comment]
I'm looking into the code on where / how to fix this. Any tips?

**Comment by xian** [comment]
Should be fixed actually -- 7b3232a207a5ea27eb06bf83e7729410d42361eb

**Comment by nzoschke** [comment]
Aha yes it is fixed! I had to re-create the scene.
