### ISSUE TITLE
README should include a .gif of the sparkle motion simulator in action

### ISSUE THREAD

**Issue by r3dcrosse** [baaahs/sparklemotion#97]
We should make a .gif of the sparkle motion simulator, and include it in our readme as one of the first things.

It makes it look cool, and gives a quick demo/overview of what this project is all about!

**Comment by tiralex** [comment]
Hello, I would like to take on this issue!

**Comment by r3dcrosse** [comment]
Yay, thank you! Please let us know if you have any issues setting up a dev environment to get the simulator running.
